development: &default
  database: vkaloidis-dev
  adapter: postgresql
  pool: 10
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: vkaloidis-dev

test:
    <<: *default
    database: vkaloidis-test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: vkaloidis_production
  username: vkaloidis
  password: <%= ENV['VKALOIDIS_DATABASE_PASSWORD'] %>
